language: go
go:
- 1.5.3
- 1.6
- tip
script: go get -v ./...
notifications:
  slack:
    secure: BpPkoFmGNuA71s0BWzcDHoK4r9ctmatY32Y4tbovVeB+14IvHfjiUSaDC4LVUP80C+C4Imcalva3x5WOmRH4tdP6yFJQdLQjaY9ZE1bg/gbPLVx8evvrALpDbFCnsriSkjGS3x4ZHpl4rCnF7ahlze8ZzD7jQ8ZPBEb69vm5LTw=
